apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: openshift-node-feature-discovery2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-node-feature-discovery2
    app.kubernetes.io/part-of: openshift-node-feature-discovery-1
  name: openshift-node-feature-discovery2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: openshift-node-feature-discovery2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: openshift-node-feature-discovery2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery-1/openshift-node-feature-discovery2@sha256:534df683f93c4cffc786125d3a2edee36b752560e83aada59b41b0dded7d63f8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
