apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: openshift-cluster-nfd-operator-cvoy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-cluster-nfd-operator-cvoy
    app.kubernetes.io/part-of: openshift-node-feature-discovery-1
  name: openshift-cluster-nfd-operator-cvoy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: openshift-cluster-nfd-operator-cvoy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: openshift-cluster-nfd-operator-cvoy
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery-1/openshift-cluster-nfd-operator-cvoy@sha256:c8be2e6c61caef5a28ec6295be2e550453207fb93d61348a760e7254d0379f0e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
